### PR TITLE
showflakes horizontal fluctuations added

### PR DESCRIPTION
**Pull request by lebedevsergey**
Snowflakes horizontal position fluctuations added - IMHO this looks better than direct line falling

### CODE REVIEW

**Comment by ptupitsyn** [comment]
Good idea, but looks like it breaks the physics and snow piles up on surfaces indefinitely:
Imgur

Also horizontal movement looks too harsh, may be we should take speed into account somehow?

**Comment by lebedevsergey** [comment]
I fixed the first point, 
but regarding snowflakes movements - it's rather the matter of taste

**Comment by ptupitsyn** [comment]
Try drawing a line and increasing speed: see how it gets "eaten" by the fluctuating flakes. I guess we need to check whether left/right pixel is occupied.

**Comment by lebedevsergey** [comment]
Fixed this, however code becomes rather ugly

**Pull request closed without merging**
